#! /bin/sh

bspc config border_width         1
bspc config window_gap           0

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true
bspc config focus_follows_pointer  true
bspc config remove_unplugged_monitors  true
bspc config top_padding  $PANEL_HEIGHT

bspc config focused_border_color #cca685
bspc config normal_border_color #0a0f0f
bspc config urgent_border_color  #f00030



bspc monitor -d Q W E A S D

bspc rule -a Gimp desktop=^8 state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Screenkey manage=off

bar.sh &
